### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by alls77** [alls77/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by anonym-collaborator** [comment]
<section>
                            <h3>Experience</h3>
                            <ul class="timeline">
                                <li>
                                    <p><i>June 2020 – present</i></p>
                                    <ul>
                                        <li class="details">
                                            <input type="checkbox" id="software-engineer">
                                            <label for="software-engineer" class="summary">
                                                <p><strong>Software engineer</strong> at <strong><a
                                                        href="https://ia.ua/" target="_blank">Infocom Ltd</a></strong>
                                                    <sup><em>Industrial automation leader (at least that's what the
                                                        director says).</em></sup></p>
                                            </label>
                                            <div>
                                                <ul>
                                                    <li>some info</li>
                                                    <li>some info</li>
                                                </ul>
                                            </div>
                                        </li>
                                    </ul>
                                <li>
                                    <p><em>21<sup>th</sup> June 2014</em></p>
                                    <p><strong>Got my internal passport</strong> (with the most awkward photo... at
                                        least it was like this before getting the pass)</p>
                                </li>
                                <li>
                                    <p><i>1998 - 2014</i></p>
                                    <p>Too much information...</p>
                                    <div style="width: 20%; height: 20%;">
                                        <lottie-player id="animation" class="canv"
                                                       src="./styles/img/loadingAnimation.json" background="transparent"
                                                       speed="1" loop autoplay></lottie-player>
                                    </div>
                                </li>
                                <li>
                                    <p><em>3<sup>th</sup> March 1998</em></p>
                                    <p>
                                        <strong>Born</strong> in <strong><a
                                            href="https://www.google.com/maps/place/%D0%97%D0%B0%D0%BF%D0%BE%D1%80%D0%BE%D0%B6%D1%8C%D0%B5,+%D0%97%D0%B0%D0%BF%D0%BE%D1%80%D0%BE%D0%B6%D1%81%D0%BA%D0%B0%D1%8F+%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C,+69000/@47.8563742,35.0352686,11z/data=!3m1!4b1!4m5!3m4!1s0x40dc673dfa85bb03:0x7e675cd9074d3f4a!8m2!3d47.8388!4d35.139567"
                                            target="_blank">Zaporizhzhia, Ukraine</a></strong><sup><em></em></sup>
                                    </p>
                                </li>
                            </ul>
                            </li>
                        </section>
