### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by alls77** [alls77/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by anonym-collaborator** [comment]
<section>
                            <h3>Languages</h3>
                            <ul class="tags small">
                                <li><p class="language" lang="ua">УКРАЇНСЬКА</p></li>
                                <li><p class="language" lang="ru">РУССКИЙ</p></li>
                                <li><p class="language" lang="en">ENGLISH</p></li>
                            </ul>
                        </section>
                        
                        <section>
                            <h3>Skills</h3>
                            <p class="tags small">
                                <span style="color: #27CFFD;">C# .NET PYTHON JS HTML CSS SQL</span>
                                <span style="color: #3da4fc;"> <span>VISUAL STUDIO</span> <span>VISUAL STUDIO CODE</span> <span>PYCHARM</span>
                <span style="color: #0088ff;"> LINUX WINDOWS</span>
                            </p>
                        </section>
                        
                        <section>
                            <h3>Character</h3>
                            <p class="tags small">CURIOUS CONSISTENT COMPETITIVE CALM PROCRASTINATOR</p>
                        </section>
                        
                        <section>
                            <h3>Likes&#x1f603;</h3>
                            <p class="tags small">BOOKS SNOWBOARDING ROBOTICS ROCK HUMOUR SELF-EDUCATION</p>
                        </section>
                        
                        <section>
                            <h3>Dislikes&#x1f61e;</h3>
                            <p class="tags small">TV POLITICS TRANSLIT <span>OWN PROCRASTINATION</span></p>
                        </section>
                        
                        <section>
                            <h3>Wants</h3>
                            <p class="none-padding-margin" style="color: #A0A0A0;">TO BE GOOD SOFTWARE ENGINEER</p>
                            <p class="none-padding-margin" style="color: #606060;">TO OWN MY SCHEDULE</p>
                            <p class="none-padding-margin" style="color: #080808;">TO READ MORE</p>
                        </section>
